# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import glob
from matplotlib.backends.backend_qt5agg import (FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from PyQt5 import QtCore, QtGui, QtWidgets
import paho.mqtt.client as mqtt
import multiprocessing
import numpy as np
import os, sys
from copy import deepcopy
import pandas as pd
from PyQt5.QtWidgets import QDialog, QApplication, QFileDialog
from PyQt5.uic import loadUi
import tkinter as tk
from tkinter import filedialog
tk.Tk().withdraw()

from FilterData import DataFilter


class Ui_MainWindow(object):
    def __init__(self, data_queue):
        super().__init__()
        self.data_queue = data_queue
        self.setupUi(MainWindow)

        def on_connect(client, userdata, flags, rc):
            # Subscribes to the user input inside the input_mqtt_topic
            print("Connected to topic: ac_phys/workxp/live_signals")
            client.subscribe("ac_phys/workxp/live_signals")          

        def on_message(client, userdata, msg):
            msg_byte = msg.payload
            msg_array = np.frombuffer(msg_byte, dtype=float, count=-1, offset=0)
            msg_full = np.reshape(msg_array, (40, 2200))
            # when we receive a message (on_message), we run the update_plot function, 
            # which plots the data as soon as it receives a message.
            print(msg_full[0])
            if useData == "Live":
                self.update_plot(np.array(msg_full))
            elif useData == "Loaded":
                global LoadedDataFrame
                DataToDisplay = iterate(LoadedDataFrame)
                self.update_plot(np.array(DataToDisplay))
                

        def on_disconnect(client, userdata, rc):
            if rc != 0:
                print("Unexpected disconnection")
            else:
                print("Disconnected")
        def iterate(LoadedDataFrame):
            global Counter
            if Counter >= len(LoadedDataFrame):
                Counter = 0
            elif Counter < len(LoadedDataFrame) - 1:
                Counter += 1
            return LoadedDataFrame[Counter] 


        self.client = mqtt.Client()
        self.client.on_connect = on_connect
        self.client.on_message = on_message
        self.client.on_disconnect = on_disconnect
        self.client.connect("130.246.57.45", 8883, 60)
        self.client.loop_start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1310, 953)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(890, 30, 411, 831))
        self.tabWidget.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.timeIntervalFrame = QtWidgets.QFrame(self.Main)
        self.timeIntervalFrame.setGeometry(QtCore.QRect(10, 30, 381, 141))
        self.timeIntervalFrame.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.timeIntervalFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.timeIntervalFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.timeIntervalFrame.setObjectName("timeIntervalFrame")
        self.timeIntervalTitle = QtWidgets.QTextBrowser(self.timeIntervalFrame)
        self.timeIntervalTitle.setGeometry(QtCore.QRect(60, 10, 256, 41))
        self.timeIntervalTitle.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"font: 11pt \"Bookshelf Symbol 7\";\n"
"border-color: rgb(157, 157, 157);")
        self.timeIntervalTitle.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.timeIntervalTitle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.timeIntervalTitle.setObjectName("timeIntervalTitle")
        self.startTime = QtWidgets.QDoubleSpinBox(self.timeIntervalFrame)
        self.startTime.setRange(-0.5, 10.5)
        self.startTime.setValue(-0.5)
        self.startTime.setGeometry(QtCore.QRect(30, 70, 121, 41))
        self.startTime.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.startTime.setObjectName("startTime")
        self.endTime = QtWidgets.QDoubleSpinBox(self.timeIntervalFrame)
        self.endTime.setRange(-0.5, 10.5)
        self.endTime.setValue(10.5)
        self.endTime.setGeometry(QtCore.QRect(240, 70, 121, 41))
        self.endTime.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.endTime.setObjectName("endTime")
        self.unitsFrame = QtWidgets.QFrame(self.Main)
        self.unitsFrame.setGeometry(QtCore.QRect(10, 200, 381, 281))
        self.unitsFrame.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.unitsFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.unitsFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.unitsFrame.setObjectName("unitsFrame")
        self.unitsTitle = QtWidgets.QTextBrowser(self.unitsFrame)
        self.unitsTitle.setGeometry(QtCore.QRect(60, 10, 256, 41))
        self.unitsTitle.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"font: 8pt \"Lucida Console\";")
        self.unitsTitle.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.unitsTitle.setObjectName("unitsTitle")
        self.mevRadiobutton = QtWidgets.QRadioButton(self.unitsFrame)
        self.mevRadiobutton.setGeometry(QtCore.QRect(50, 70, 251, 51))
        self.mevRadiobutton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.mevRadiobutton.setObjectName("mevRadiobutton")
        self.coulombsRadiobutton = QtWidgets.QRadioButton(self.unitsFrame)
        self.coulombsRadiobutton.setGeometry(QtCore.QRect(50, 130, 181, 20))
        self.coulombsRadiobutton.setToolTipDuration(-3)
        self.coulombsRadiobutton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.coulombsRadiobutton.setObjectName("coulombsRadiobutton")
        self.protonsRadiobutton = QtWidgets.QRadioButton(self.unitsFrame)
        self.protonsRadiobutton.setGeometry(QtCore.QRect(50, 180, 131, 20))
        self.protonsRadiobutton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.protonsRadiobutton.setObjectName("protonsRadiobutton")
        self.joulesRadiobutton = QtWidgets.QRadioButton(self.unitsFrame)
        self.joulesRadiobutton.setGeometry(QtCore.QRect(50, 220, 161, 20))
        self.joulesRadiobutton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.joulesRadiobutton.setObjectName("joulesRadiobutton")
        self.barColoursFrame = QtWidgets.QFrame(self.Main)
        self.barColoursFrame.setGeometry(QtCore.QRect(10, 510, 381, 271))
        self.barColoursFrame.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.barColoursFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.barColoursFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.barColoursFrame.setObjectName("barColoursFrame")
        self.keyFrame = QtWidgets.QStackedWidget(self.barColoursFrame)
        self.keyFrame.setGeometry(QtCore.QRect(100, 120, 191, 131))
        self.keyFrame.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.keyFrame.setObjectName("keyFrame")
        self.defaultColourPage = QtWidgets.QWidget()
        self.defaultColourPage.setObjectName("defaultColourPage")
        self.defaultKeyTitle = QtWidgets.QTextBrowser(self.defaultColourPage)
        self.defaultKeyTitle.setGeometry(QtCore.QRect(50, 0, 91, 31))
        self.defaultKeyTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.defaultKeyTitle.setObjectName("defaultKeyTitle")
        self.defaultSumColour = QtWidgets.QTextBrowser(self.defaultColourPage)
        self.defaultSumColour.setGeometry(QtCore.QRect(20, 50, 21, 21))
        self.defaultSumColour.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.defaultSumColour.setObjectName("defaultSumColour")
        self.defaultTolColour = QtWidgets.QTextBrowser(self.defaultColourPage)
        self.defaultTolColour.setGeometry(QtCore.QRect(20, 90, 21, 21))
        self.defaultTolColour.setStyleSheet("background-color: rgb(108, 187, 60)")
        self.defaultTolColour.setObjectName("defaultTolColour")
        self.defaultSumLabel = QtWidgets.QLabel(self.defaultColourPage)
        self.defaultSumLabel.setGeometry(QtCore.QRect(80, 50, 55, 16))
        self.defaultSumLabel.setObjectName("defaultSumLabel")
        self.defaultTolLabel = QtWidgets.QLabel(self.defaultColourPage)
        self.defaultTolLabel.setGeometry(QtCore.QRect(60, 90, 71, 16))
        self.defaultTolLabel.setObjectName("defaultTolLabel")
        self.keyFrame.addWidget(self.defaultColourPage)
        self.altColourPage = QtWidgets.QWidget()
        self.altColourPage.setObjectName("altColourPage")
        self.altSumColour = QtWidgets.QTextBrowser(self.altColourPage)
        self.altSumColour.setGeometry(QtCore.QRect(20, 50, 21, 21))
        self.altSumColour.setStyleSheet("background-color: rgb(245, 118, 0);\n"
"background-color: rgb(79, 227, 243);")
        self.altSumColour.setObjectName("altSumColour")
        self.altTolColour = QtWidgets.QTextBrowser(self.altColourPage)
        self.altTolColour.setGeometry(QtCore.QRect(20, 90, 21, 21))
        self.altTolColour.setStyleSheet("background-color: rgb(0, 115, 230);")
        self.altTolColour.setObjectName("altTolColour")
        self.altSumLabel = QtWidgets.QLabel(self.altColourPage)
        self.altSumLabel.setGeometry(QtCore.QRect(80, 50, 55, 16))
        self.altSumLabel.setObjectName("altSumLabel")
        self.altTolLabel = QtWidgets.QLabel(self.altColourPage)
        self.altTolLabel.setGeometry(QtCore.QRect(60, 90, 71, 16))
        self.altTolLabel.setObjectName("altTolLabel")
        self.altKeyTitle = QtWidgets.QTextBrowser(self.altColourPage)
        self.altKeyTitle.setGeometry(QtCore.QRect(50, 0, 91, 31))
        self.altKeyTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.altKeyTitle.setObjectName("altKeyTitle")
        self.keyFrame.addWidget(self.altColourPage)
        self.defaultColourscheme = QtWidgets.QRadioButton(self.barColoursFrame)
        self.defaultColourscheme.setGeometry(QtCore.QRect(60, 80, 95, 20))
        self.defaultColourscheme.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.defaultColourscheme.setObjectName("defaultColourscheme")
        self.altColourscheme = QtWidgets.QRadioButton(self.barColoursFrame)
        self.altColourscheme.setGeometry(QtCore.QRect(210, 80, 121, 20))
        self.altColourscheme.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.altColourscheme.setObjectName("altColourscheme")
        self.barColoursTitle = QtWidgets.QTextBrowser(self.barColoursFrame)
        self.barColoursTitle.setGeometry(QtCore.QRect(80, 10, 221, 41))
        self.barColoursTitle.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.barColoursTitle.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.barColoursTitle.setObjectName("barColoursTitle")
        self.tabWidget.addTab(self.Main, "")
        self.Demo = QtWidgets.QWidget()
        self.Demo.setObjectName("Demo")
        self.dataRetrievalTitle = QtWidgets.QTextBrowser(self.Demo)
        self.dataRetrievalTitle.setGeometry(QtCore.QRect(110, 20, 171, 41))
        self.dataRetrievalTitle.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"font: 8pt \"Lucida Console\";")
        self.dataRetrievalTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dataRetrievalTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataRetrievalTitle.setObjectName("dataRetrievalTitle")
        self.dataRetrievalFrame = QtWidgets.QFrame(self.Demo)
        self.dataRetrievalFrame.setGeometry(QtCore.QRect(30, 90, 351, 151))
        self.dataRetrievalFrame.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.dataRetrievalFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.dataRetrievalFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dataRetrievalFrame.setObjectName("dataRetrievalFrame")
        self.fileSearchBox = QtWidgets.QLineEdit(self.dataRetrievalFrame)
        self.fileSearchBox.setGeometry(QtCore.QRect(70, 110, 113, 22))
        self.fileSearchBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.fileSearchBox.setObjectName("fileSearchBox")
        self.liveSigButton = QtWidgets.QRadioButton(self.dataRetrievalFrame)
        self.liveSigButton.setGeometry(QtCore.QRect(40, 30, 151, 20))
        self.liveSigButton.setObjectName("liveSigButton")
        self.uploadDataButton = QtWidgets.QRadioButton(self.dataRetrievalFrame)
        self.uploadDataButton.setGeometry(QtCore.QRect(40, 80, 171, 21))
        self.uploadDataButton.setObjectName("uploadDataButton")
        self.browseButton = QtWidgets.QPushButton(self.dataRetrievalFrame)
        self.browseButton.setGeometry(QtCore.QRect(190, 110, 93, 21))
        self.browseButton.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.browseButton.setObjectName("browseButton")
        self.connectButton = QtWidgets.QPushButton(self.Demo)
        self.connectButton.setGeometry(QtCore.QRect(20, 260, 171, 51))
        self.connectButton.setStyleSheet("background-color: rgb(107, 170, 67)")
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.Demo)
        self.disconnectButton.setGeometry(QtCore.QRect(220, 260, 171, 51))
        self.disconnectButton.setStyleSheet("background-color: rgb(144, 0, 0);")
        self.disconnectButton.setObjectName("disconnectButton")
        self.tabWidget.addTab(self.Demo, "")
        self.Callibration = QtWidgets.QWidget()
        self.Callibration.setObjectName("Callibration")
        self.seeFrame = QtWidgets.QFrame(self.Callibration)
        self.seeFrame.setGeometry(QtCore.QRect(20, 20, 371, 221))
        self.seeFrame.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.seeFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.seeFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seeFrame.setObjectName("seeFrame")
        self.seeTitle = QtWidgets.QTextBrowser(self.seeFrame)
        self.seeTitle.setGeometry(QtCore.QRect(60, 10, 251, 71))
        self.seeTitle.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.seeTitle.setObjectName("seeTitle")
        self.defaultEnergyButton = QtWidgets.QRadioButton(self.seeFrame)
        self.defaultEnergyButton.setGeometry(QtCore.QRect(40, 100, 231, 20))
        self.defaultEnergyButton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.defaultEnergyButton.setObjectName("defaultEnergyButton")
        self.customEnergyButton = QtWidgets.QRadioButton(self.seeFrame)
        self.customEnergyButton.setGeometry(QtCore.QRect(40, 150, 261, 21))
        self.customEnergyButton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.customEnergyButton.setObjectName("customEnergyButton")
        self.inputEnergyBox = QtWidgets.QTextEdit(self.seeFrame)
        self.inputEnergyBox.setGeometry(QtCore.QRect(140, 180, 101, 31))
        self.inputEnergyBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputEnergyBox.setObjectName("inputEnergyBox")
        self.toleranceFrame = QtWidgets.QFrame(self.Callibration)
        self.toleranceFrame.setGeometry(QtCore.QRect(20, 280, 371, 481))
        self.toleranceFrame.setStyleSheet("background-color: rgb(141, 141, 141);")
        self.toleranceFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.toleranceFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toleranceFrame.setObjectName("toleranceFrame")
        self.toleranceTitle = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.toleranceTitle.setGeometry(QtCore.QRect(70, 10, 231, 41))
        self.toleranceTitle.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.toleranceTitle.setObjectName("toleranceTitle")
        self.defaultTolButton = QtWidgets.QRadioButton(self.toleranceFrame)
        self.defaultTolButton.setGeometry(QtCore.QRect(40, 80, 231, 20))
        self.defaultTolButton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.defaultTolButton.setObjectName("defaultTolButton")
        self.customTolButton = QtWidgets.QRadioButton(self.toleranceFrame)
        self.customTolButton.setGeometry(QtCore.QRect(40, 140, 261, 21))
        self.customTolButton.setStyleSheet("font: 8pt \"Lucida Console\";")
        self.customTolButton.setObjectName("customTolButton")
        self.R0comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R0comboBox.setGeometry(QtCore.QRect(80, 170, 73, 22))
        self.R0comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R0comboBox.setObjectName("R0comboBox")
        self.R0comboBox.addItem("")
        self.R0comboBox.addItem("")
        self.R0comboBox.addItem("")
        self.R1comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R1comboBox.setGeometry(QtCore.QRect(80, 200, 73, 22))
        self.R1comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R1comboBox.setObjectName("R1comboBox")
        self.R1comboBox.addItem("")
        self.R1comboBox.addItem("")
        self.R1comboBox.addItem("")
        self.R1comboBox.addItem("")
        self.R5comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R5comboBox.setGeometry(QtCore.QRect(80, 320, 73, 22))
        self.R5comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R5comboBox.setObjectName("R5comboBox")
        self.R5comboBox.addItem("")
        self.R5comboBox.addItem("")
        self.R5comboBox.addItem("")
        self.R5comboBox.addItem("")
        self.R2comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R2comboBox.setGeometry(QtCore.QRect(80, 230, 73, 22))
        self.R2comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R2comboBox.setObjectName("R2comboBox")
        self.R2comboBox.addItem("")
        self.R2comboBox.addItem("")
        self.R2comboBox.addItem("")
        self.R2comboBox.addItem("")
        self.R3comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R3comboBox.setGeometry(QtCore.QRect(80, 260, 73, 22))
        self.R3comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R3comboBox.setObjectName("R3comboBox")
        self.R3comboBox.addItem("")
        self.R3comboBox.addItem("")
        self.R3comboBox.addItem("")
        self.R3comboBox.addItem("")
        self.R4comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R4comboBox.setGeometry(QtCore.QRect(80, 290, 73, 22))
        self.R4comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R4comboBox.setObjectName("R4comboBox")
        self.R4comboBox.addItem("")
        self.R4comboBox.addItem("")
        self.R4comboBox.addItem("")
        self.R4comboBox.addItem("")
        self.R9comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R9comboBox.setGeometry(QtCore.QRect(80, 440, 73, 22))
        self.R9comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R9comboBox.setObjectName("R9comboBox")
        self.R9comboBox.addItem("")
        self.R9comboBox.addItem("")
        self.R9comboBox.addItem("")
        self.R9comboBox.addItem("")
        self.R8comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R8comboBox.setGeometry(QtCore.QRect(80, 410, 73, 22))
        self.R8comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R8comboBox.setObjectName("R8comboBox")
        self.R8comboBox.addItem("")
        self.R8comboBox.addItem("")
        self.R8comboBox.addItem("")
        self.R8comboBox.addItem("")
        self.R7comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R7comboBox.setGeometry(QtCore.QRect(80, 380, 73, 22))
        self.R7comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R7comboBox.setObjectName("R7comboBox")
        self.R7comboBox.addItem("")
        self.R7comboBox.addItem("")
        self.R7comboBox.addItem("")
        self.R7comboBox.addItem("")
        self.R6comboBox = QtWidgets.QComboBox(self.toleranceFrame)
        self.R6comboBox.setGeometry(QtCore.QRect(80, 350, 73, 22))
        self.R6comboBox.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R6comboBox.setObjectName("R6comboBox")
        self.R6comboBox.addItem("")
        self.R6comboBox.addItem("")
        self.R6comboBox.addItem("")
        self.R6comboBox.addItem("")
        self.R0box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R0box.setGeometry(QtCore.QRect(170, 170, 113, 22))
        self.R0box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R0box.setObjectName("R0box")
        self.R1box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R1box.setGeometry(QtCore.QRect(170, 200, 113, 22))
        self.R1box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R1box.setObjectName("R1box")
        self.R2box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R2box.setGeometry(QtCore.QRect(170, 230, 113, 22))
        self.R2box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R2box.setObjectName("R2box")
        self.R3box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R3box.setGeometry(QtCore.QRect(170, 260, 113, 22))
        self.R3box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R3box.setObjectName("R3box")
        self.R4box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R4box.setGeometry(QtCore.QRect(170, 290, 113, 22))
        self.R4box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R4box.setObjectName("R4box")
        self.R5box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R5box.setGeometry(QtCore.QRect(170, 320, 113, 22))
        self.R5box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R5box.setObjectName("R5box")
        self.R6box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R6box.setGeometry(QtCore.QRect(170, 350, 113, 22))
        self.R6box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R6box.setObjectName("R6box")
        self.R7box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R7box.setGeometry(QtCore.QRect(170, 380, 113, 22))
        self.R7box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R7box.setObjectName("R7box")
        self.R8box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R8box.setGeometry(QtCore.QRect(170, 410, 113, 22))
        self.R8box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R8box.setObjectName("R8box")
        self.R9box = QtWidgets.QLineEdit(self.toleranceFrame)
        self.R9box.setGeometry(QtCore.QRect(170, 440, 113, 22))
        self.R9box.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.R9box.setObjectName("R9box")
        self.R0add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R0add.setGeometry(QtCore.QRect(320, 170, 41, 28))
        self.R0add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R0add.setObjectName("R0add")
        self.R1add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R1add.setGeometry(QtCore.QRect(320, 200, 41, 28))
        self.R1add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R1add.setObjectName("R1add")
        self.R2add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R2add.setGeometry(QtCore.QRect(320, 230, 41, 28))
        self.R2add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R2add.setObjectName("R2add")
        self.R3add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R3add.setGeometry(QtCore.QRect(320, 260, 41, 28))
        self.R3add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R3add.setObjectName("R3add")
        self.R4add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R4add.setGeometry(QtCore.QRect(320, 290, 41, 28))
        self.R4add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R4add.setObjectName("R4add")
        self.R5add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R5add.setGeometry(QtCore.QRect(320, 320, 41, 28))
        self.R5add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R5add.setObjectName("R5add")
        self.R6add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R6add.setGeometry(QtCore.QRect(320, 350, 41, 28))
        self.R6add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R6add.setObjectName("R6add")
        self.R7add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R7add.setGeometry(QtCore.QRect(320, 380, 41, 28))
        self.R7add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R7add.setObjectName("R7add")
        self.R8add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R8add.setGeometry(QtCore.QRect(320, 410, 41, 28))
        self.R8add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R8add.setObjectName("R8add")
        self.R9add = QtWidgets.QPushButton(self.toleranceFrame)
        self.R9add.setGeometry(QtCore.QRect(320, 440, 41, 28))
        self.R9add.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.R9add.setObjectName("R9add")
        self.R0label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R0label.setGeometry(QtCore.QRect(10, 170, 61, 41))
        self.R0label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R0label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R0label.setObjectName("R0label")
        self.R1label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R1label.setGeometry(QtCore.QRect(10, 200, 61, 41))
        self.R1label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R1label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R1label.setObjectName("R1label")
        self.R4label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R4label.setGeometry(QtCore.QRect(10, 290, 61, 41))
        self.R4label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R4label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R4label.setObjectName("R4label")
        self.R3label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R3label.setGeometry(QtCore.QRect(10, 260, 61, 41))
        self.R3label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R3label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R3label.setObjectName("R3label")
        self.R2label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R2label.setGeometry(QtCore.QRect(10, 230, 61, 41))
        self.R2label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R2label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R2label.setObjectName("R2label")
        self.R9label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R9label.setGeometry(QtCore.QRect(10, 440, 61, 41))
        self.R9label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R9label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R9label.setObjectName("R9label")
        self.R8label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R8label.setGeometry(QtCore.QRect(10, 410, 61, 41))
        self.R8label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R8label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R8label.setObjectName("R8label")
        self.R7label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R7label.setGeometry(QtCore.QRect(10, 380, 61, 41))
        self.R7label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R7label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R7label.setObjectName("R7label")
        self.R6label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R6label.setGeometry(QtCore.QRect(10, 350, 61, 41))
        self.R6label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R6label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R6label.setObjectName("R6label")
        self.R5label = QtWidgets.QTextBrowser(self.toleranceFrame)
        self.R5label.setGeometry(QtCore.QRect(10, 320, 61, 41))
        self.R5label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.R5label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.R5label.setObjectName("R5label")
        self.line = QtWidgets.QFrame(self.toleranceFrame)
        self.line.setGeometry(QtCore.QRect(60, 170, 20, 301))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.R0comboBox.raise_()
        self.toleranceTitle.raise_()
        self.defaultTolButton.raise_()
        self.customTolButton.raise_()
        self.R1comboBox.raise_()
        self.R5comboBox.raise_()
        self.R2comboBox.raise_()
        self.R3comboBox.raise_()
        self.R4comboBox.raise_()
        self.R9comboBox.raise_()
        self.R8comboBox.raise_()
        self.R7comboBox.raise_()
        self.R6comboBox.raise_()
        self.R0box.raise_()
        self.R1box.raise_()
        self.R2box.raise_()
        self.R3box.raise_()
        self.R4box.raise_()
        self.R5box.raise_()
        self.R6box.raise_()
        self.R7box.raise_()
        self.R8box.raise_()
        self.R9box.raise_()
        self.R0add.raise_()
        self.R1add.raise_()
        self.R2add.raise_()
        self.R3add.raise_()
        self.R4add.raise_()
        self.R5add.raise_()
        self.R6add.raise_()
        self.R7add.raise_()
        self.R8add.raise_()
        self.R9add.raise_()
        self.R0label.raise_()
        self.R1label.raise_()
        self.R2label.raise_()
        self.R3label.raise_()
        self.R4label.raise_()
        self.R5label.raise_()
        self.R6label.raise_()
        self.R7label.raise_()
        self.R8label.raise_()
        self.R9label.raise_()
        self.line.raise_()
        self.tabWidget.addTab(self.Callibration, "")

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 40, 821, 811))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        self.fig = Figure(figsize = [9,3])
        self.static_canvas = FigureCanvas(self.fig)
        # self.toolbar = NavigationToolbar(self.static_canvas, self)

        self.gridLayout.addWidget(self.static_canvas)
        # self.gridLayout.addWidget(self.toolbar)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1310, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.keyFrame.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.defaultColourscheme.clicked.connect(self.defaultBarColour)
        self.altColourscheme.clicked.connect(self.colorblindBarColour)
        self.connectButton.clicked.connect(self.Run)
        self.disconnectButton.clicked.connect(self.StopRun)
        self.browseButton.clicked.connect(self.browsefiles)
        self.liveSigButton.clicked.connect(self.MQTTData)
        self.uploadDataButton.clicked.connect(self.LoadedData)
        #self.mevRadiobutton.clicked.connect(self.convert("MeV"))
        #self.coulombsRadiobutton.clicked.connect(self.convert("C"))
        #self.protonsRadiobutton.clicked.connect(self.convert("p"))
        #self.joulesRadiobutton.clicked.connect(self.convert("J"))

    def Run(self):
        global run 
        run = True
    def StopRun(self):
        global run
        run = False

    def defaultBarColour(self):
        global colors
        colors = ["r", "#6CBB3C"]
        self.defaultSumColour.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.defaultTolColour.setStyleSheet("background-color: rgb(108, 187, 60);")

    def colorblindBarColour(self):
        global colors
        colors = ["#F57600", "#0073E6"]
        self.defaultSumColour.setStyleSheet("background-color: rgb(245, 118, 0);")
        self.defaultTolColour.setStyleSheet("background-color: rgb(0, 115, 230);")

    def browsefiles(self):
        global LoadedDataFrame
        LoadedDataFrame = []
        folder_path = filedialog.askdirectory()
        files = glob.glob(str(folder_path) + '/*.csv')
        for file in files:
                selected_file = file
                input_data = pd.read_csv(selected_file)
                tempdata = input_data.drop(columns = input_data.columns[0]).to_numpy()
                LoadedDataFrame.append(tempdata)
        global Counter
        Counter = 0
        print(LoadedDataFrame)

    def MQTTData(self):
        global useData
        useData = "Live"

    def LoadedData(self):
        global useData
        useData = "Loaded"
    def findnearest(self, x_data, time: list = [10.1, 10.5]):
            print(time)
            try:
                firstidx = np.where(x_data == time[0])[0][0]
                lastidx = np.where(x_data == time[1])[0][0]
            except:
                x_data = np.asarray(x_data)
                firstidx = (np.abs(x_data - time[0])).argmin()
                lastidx = (np.abs(x_data - time[1])).argmin()
            print([firstidx, lastidx])
            return [firstidx, lastidx]

    def CreateBar(self, data, startingtime, endingtime):
        totals = []
        for i in data:
                timeinterval = self.findnearest(np.linspace(-0.5, 10.5, 2200), [startingtime, endingtime])
                temptotal = np.sum(i[timeinterval[0]:timeinterval[1]])
                totals.append(temptotal)
        x = np.linspace(1, 39, 39)
        return (x, totals[:-1])


    def filterit(self, dataframe, minvalue = 0):
        print("Dataframe!", dataframe)
        filterer = DataFilter()
        filterer.set("auto_offset", self.findnearest(np.linspace(-0.5, 10.5, 2200)))
        dataframe = filterer.apply(dataframe)
        for each in dataframe:
            each[each < 0] = 0
        return dataframe
    
    def update_plot(self, data):
        blms=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39]
        tolerances=[0.05,0.10,0.05,0.05,0.28,2.80,2.80,0.47,0.19,0.19,0.19,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05]
        global colors
        # program radiobutton to append selected colours into this thingy
        #defaultcolors = ["r", "#6CBB3C"]
        altcolors = ["#F57600", "#0073E6"]
        y_label = "Volts"

        if run == True:
                self.fig.clear()
                self.fig.subplots_adjust(top=0.925, bottom=0.13, left=0.085, right=0.95)
                self.ax = self.fig.add_subplot(111)
                dataframe = deepcopy(data)
                dataframe = self.filterit(dataframe)
                data = self.CreateBar(dataframe, self.startTime.value(), self.endTime.value())
                self.ax.set_yscale('log')
                self.ax.set_ylim(10**-2, 10**2)
                self.ax.set_xlabel("Beam Loss Monitors")
                self.ax.set_ylabel(y_label)
                self.ax.bar(np.linspace(1, 39, 39), data[1], color = colors[0])
                self.ax.set_yscale('log')
                self.ax.set_ylim(10**-2, 10**2)
                self.ax.bar(blms, tolerances, color = colors[1])
                self.static_canvas.draw()
        elif run == False:
             print("We are disconnected")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeIntervalTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bookshelf Symbol 7\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; text-decoration: underline;\">Time Interval</span></p></body></html>"))
        self.unitsTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; text-decoration: underline;\">Units</span></p></body></html>"))
        self.mevRadiobutton.setText(_translate("MainWindow", "Mega electron Volts (MeV)"))
        self.coulombsRadiobutton.setText(_translate("MainWindow", "Coulombs (C)"))
        self.protonsRadiobutton.setText(_translate("MainWindow", "Protons ()"))
        self.joulesRadiobutton.setText(_translate("MainWindow", "Joules (J)"))
        self.defaultKeyTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-style:italic;\">KEY:</span></p></body></html>"))
        self.defaultSumLabel.setText(_translate("MainWindow", "SUM"))
        self.defaultTolLabel.setText(_translate("MainWindow", "TOLERANCE"))
        self.altSumLabel.setText(_translate("MainWindow", "SUM"))
        self.altTolLabel.setText(_translate("MainWindow", "TOLERANCE"))
        self.altKeyTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-style:italic;\">KEY:</span></p></body></html>"))
        self.defaultColourscheme.setText(_translate("MainWindow", "default"))
        self.altColourscheme.setText(_translate("MainWindow", "colorblind"))
        self.barColoursTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; text-decoration: underline; color:#000000;\">Bar Colours</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), _translate("MainWindow", "Main GUI"))
        self.dataRetrievalTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Console\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">Data Retrieval:</span></p></body></html>"))
        self.fileSearchBox.setText(_translate("MainWindow", "SELECT FILE BEFORE CLICKING THE 'Load Stored Data Button'"))
        self.liveSigButton.setText(_translate("MainWindow", "Live Signal  (MQTT)"))
        self.uploadDataButton.setText(_translate("MainWindow", "Load stored data (.csv)"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Demo), _translate("MainWindow", "Demo Mode"))
        self.seeTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; text-decoration: underline;\">Synchrotron Extraction Energy</span></p></body></html>"))
        self.defaultEnergyButton.setText(_translate("MainWindow", "Default Energy (800MeV)"))
        self.customEnergyButton.setText(_translate("MainWindow", "Customise Extraction Energy:"))
        self.inputEnergyBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Type here...</span></p></body></html>"))
        self.toleranceTitle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; text-decoration: underline;\">Tolerance</span></p></body></html>"))
        self.defaultTolButton.setText(_translate("MainWindow", "Default Tolerance"))
        self.customTolButton.setText(_translate("MainWindow", "Customise Tolerance:"))
        self.R0comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R0comboBox.setItemText(1, _translate("MainWindow", "BLM3"))
        self.R0comboBox.setItemText(2, _translate("MainWindow", "BLM4"))
        self.R1comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R1comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R1comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R1comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R5comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R5comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R5comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R5comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R2comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R2comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R2comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R2comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R3comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R3comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R3comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R3comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R4comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R4comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R4comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R4comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R9comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R9comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R9comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R9comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R8comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R8comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R8comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R8comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R7comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R7comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R7comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R7comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R6comboBox.setItemText(0, _translate("MainWindow", "BLM1"))
        self.R6comboBox.setItemText(1, _translate("MainWindow", "BLM2"))
        self.R6comboBox.setItemText(2, _translate("MainWindow", "BLM3"))
        self.R6comboBox.setItemText(3, _translate("MainWindow", "BLM4"))
        self.R0add.setText(_translate("MainWindow", "Add"))
        self.R1add.setText(_translate("MainWindow", "Add"))
        self.R2add.setText(_translate("MainWindow", "Add"))
        self.R3add.setText(_translate("MainWindow", "Add"))
        self.R4add.setText(_translate("MainWindow", "Add"))
        self.R5add.setText(_translate("MainWindow", "Add"))
        self.R6add.setText(_translate("MainWindow", "Add"))
        self.R7add.setText(_translate("MainWindow", "Add"))
        self.R8add.setText(_translate("MainWindow", "Add"))
        self.R9add.setText(_translate("MainWindow", "Add"))
        self.R0label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R0</span></p></body></html>"))
        self.R1label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R1</span></p></body></html>"))
        self.R4label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R4</span></p></body></html>"))
        self.R3label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R3</span></p></body></html>"))
        self.R2label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R2</span></p></body></html>"))
        self.R9label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R9</span></p></body></html>"))
        self.R8label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R8</span></p></body></html>"))
        self.R7label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R7</span></p></body></html>"))
        self.R6label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R6</span></p></body></html>"))
        self.R5label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">R5</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Callibration), _translate("MainWindow", "Callibration/Settings"))


if __name__ == "__main__":
    import sys
    global useData
    useData = "Live"
    global run
    run = False
    global colors
    colors = ["r", "#6CBB3C"]
    data_queue = multiprocessing.Queue()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(data_queue)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
